# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amel Ghouila, PhD
email: amel.ghouila@gmail.com
description1: Women's Empowerement Advocate
description2: Open Science Enthusiast
description3: Capacity Builder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: AmelGhouila 
github_username: amelgh

# Build settings
markdown: kramdown

# For SEO optimization
gems:
  - jekyll-seo-tag

# Enable linking to header anchors
kramdown:
  auto_ids: true
